package=ifetch
source=https://github.com/Ietsiee/ifetch/archive/refs/heads/main.tar.gz
type=tar.gz
prepare="cp -r /tmp/$package/ifetch-main/* /tmp/$package/"
build="chmod +x modules/* ifetch.sh ifetch-launcher.sh"
install="mkdir -p /etc/ifetch && cp ifetch-launcher.sh /usr/local/bin/ifetch && cp ifetch.sh /etc/ifetch/ifetch.sh && cp -r modules /etc/ifetch/modules && cp help.txt /etc/ifetch/help.txt && cp logo.txt /etc/ifetch/logo.txt && cp ifetch.config /etc/ifetch/ifetch.config"
