#!/bin/sh

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev

echo
echo "Welcome to GreenOS"
echo
echo "Run green-setup to start the setup"

exec setsid cttyhack /bin/sh
